# Generated by Django 5.1.4 on 2025-01-07 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
