# Generated by Django 5.1.4 on 2025-01-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(default='undelivered', max_length=50),
        ),
    ]
