# Generated by Django 5.1.4 on 2025-01-07 04:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0004_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivered_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
