# Generated by Django 5.1.4 on 2025-01-07 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0005_product_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
