# Generated by Django 5.1.3 on 2024-11-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0005_alter_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
