# Generated by Django 5.1.4 on 2025-01-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('post', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
