# Generated by Django 5.1.4 on 2025-01-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'concert category',
                'verbose_name_plural': 'concert categories',
                'ordering': ['-name'],
            },
        ),
    ]
